# Generated by Django 4.2.5 on 2023-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AQI",
            fields=[
                (
                    "STATE",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("MONTH", models.CharField(max_length=20)),
                ("PM", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="WQI",
            fields=[
                (
                    "STATE",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("MONTH", models.CharField(max_length=20)),
                ("TEMP", models.FloatField(default=0)),
                ("DO", models.FloatField(default=0)),
                ("PH", models.FloatField(default=0)),
                ("BOD", models.FloatField(default=0)),
                ("NITRITE", models.FloatField(default=0)),
                ("FECAL", models.FloatField(default=0)),
                ("TOTALCOLIFORM", models.FloatField(default=0)),
            ],
        ),
    ]
