# Generated by Django 4.2.5 on 2023-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_aqi_result_wqi_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="wqi",
            name="TDS",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="wqi",
            name="TURB",
            field=models.FloatField(default=0),
        ),
    ]
