# Generated by Django 4.2.5 on 2023-09-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_wqi_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="wqi",
            name="COND",
            field=models.FloatField(default=0),
        ),
    ]
