# Generated by Django 4.2.5 on 2023-09-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_wqi_cond"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aqi",
            name="PM",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="BOD",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="COND",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="DO",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="FECAL",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="NITRITE",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="PH",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="TDS",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="TEMP",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="TOTALCOLIFORM",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="wqi",
            name="TURB",
            field=models.FloatField(default=0, null=True),
        ),
    ]
